#!/bin/sh
# Copyright (c) 2020, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

busybox.suid mount -n -o mode=0755 -t devtmpfs none "/dev"
busybox echo "mounted devtmpfsr"
busybox.suid mount proc /proc -t proc
busybox echo "mounted proc"
busybox mknod /dev/nd_0 b 252 0
busybox.suid mount -o remount,rw  /
busybox mkdir -p /mnt/vfs

# verity protection
if [ -f /etc/verity.env ]; then
    source /etc/verity.env
    veritysetup open /dev/nd_0 system /dev/nd_0 $VERITY_ROOT_HASH --salt $VERITY_SALT --hash-offset $VERITY_HASH_OFFSET --data-blocks $VERITY_DATA_BLOCKS --fec-device /dev/nd_0 --fec-offset $VERITY_FEC_OFFSET --fec-roots $VERITY_FEC_ROOTS
    busybox.suid mount -t ext4 -o ro /dev/mapper/system /mnt/vfs
else
    busybox.suid mount -t ext4 -o ro /dev/nd_0 /mnt/vfs
fi

busybox ls -la /mnt/vfs
busybox echo "Switching root"
exec busybox switch_root -c /dev/console /mnt/vfs /sbin/init
