#! /bin/sh
# Copyright (c) 2023, Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Load dsp-kernel module
export MODULE_BASE=/usr/lib/modules/
set -e

case "$1" in
    start)
    echo -n "Starting/Loading Fastrpc dsp_kernel module: "

    echo "dsp_kernel:start/load" > /dev/kmsg
    insmod $MODULE_BASE/frpc-trusted-adsprpc.ko

    echo "done loading dsp_kernel module"
    ;;
    stop)
    echo -n "Bypassing Unloading of dsp_kernel modules "
    ;;
    restart)
    $0 stop
    $0 start
    ;;
    *)
    echo "Usage { start | stop | restart}" >&2
    exit 1
    ;;
esac

exit 0



