#!/bin/sh
# Copyright (c) 2020, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Perform a bind mount, copying existing files as we do so to ensure the
#!/bin/sh
#
# Perform a bind mount, copying existing files as we do so to ensure the
# overlaid path has the necessary content.

if [ ! -e "$2" ]; then
   echo >&2 "No System file/directory exist"
   exit 1
fi

spec=$1
mountpoint=$2

if [ -f "$mountpoint" ]; then
    #Skip if already mount-binded
    if grep -qs $mountpoint /proc/mounts; then
        exit 0
    fi

    if [ ! -f "$spec" ]; then
        mkdir -p $(dirname $spec)
        cp -P --preserve=all "$mountpoint" "$spec"
    fi

    mount -o "bind" "$spec" "$mountpoint"
fi

if [ -d "$mountpoint" ]; then
    mkdir -p $spec
    cd $mountpoint
    for file in *
    do
        #Skip if already mount-binded
        # remove trailing '/' if present
        mountpath=$(echo $mountpoint | sed 's:/*$::')
        if grep -qs "$mountpath/$file" /proc/mounts; then
            continue
        fi

        if [ -f "$mountpoint/$file" ]; then
            if [ ! -f "$spec/$file" ]; then
                cp --preserve=all "$file" "$spec/"
            fi
            mount -o "bind" "$spec/$file" "$mountpoint/$file"
        fi
   done
fi
